/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soundcloud_android_jni_NativeAmplitudeAnalyzer */

#ifndef _Included_com_soundcloud_android_jni_NativeAmplitudeAnalyzer
#define _Included_com_soundcloud_android_jni_NativeAmplitudeAnalyzer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soundcloud_android_jni_NativeAmplitudeAnalyzer
 * Method:    frameAmplitude
 * Signature: (Ljava/nio/ByteBuffer;I)F
 */
JNIEXPORT jfloat JNICALL Java_com_soundcloud_android_jni_NativeAmplitudeAnalyzer_frameAmplitude
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_soundcloud_android_jni_NativeAmplitudeAnalyzer
 * Method:    getLastValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_NativeAmplitudeAnalyzer_getLastValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
