release:
  mvn: &defaults_mvn
    tasks: &defaults_tasks
      build: &defaults_build
        phase: install
        project: app
        tests: false
        proguard: true
        profiles:
          - sign
          - soundcloud
          - release
      unittests: &defaults_unittests
        phase: test
        project: app
        tests: true
        profiles:
          - release
      phone_test: &defaults_phone_test
        phase: install
        project: tests-integration
        tests: true
        profiles:
          - sign
          - release
          - soundcloud
          - phone-test
debug:
  mvn:
    <<: *defaults_mvn
    tasks:
      <<: *defaults_tasks
      build:
        <<: *defaults_build
        phase: install
        tests: false
        profiles:
          - debug
          - sign
          - update-android-manifest
      unittests:
        <<: *defaults_unittests
        profiles:
          - debug
          - coverage
      phone_test:
        phase: install
        project: tests-integration
        tests: true
        profiles:
          - sign
          - debug
          - phone-test
end2end:
  mvn:
    <<: *defaults_mvn
    tasks:
      <<: *defaults_tasks
      build:
        <<: *defaults_build
        phase: install
        tests: false
        profiles:
          - end2end
          - sign
          - update-android-manifest
      unittests:
        <<: *defaults_unittests
        profiles:
          - end2end
          - coverage
      phone_test:
        phase: install
        project: tests-integration
        tests: true
        profiles:
          - sign
          - debug
          - phone-test
beta:
  mvn:
    <<: *defaults_mvn
    tasks:
      build:
        <<: *defaults_build
        tests: false
        profiles:
          - beta
          - sign
          - soundcloud
          - update-android-manifest
alpha:
  mvn:
    <<: *defaults_mvn
    tasks:
      build:
        <<: *defaults_build
        tests: false
        profiles:
          - alpha
          - sign
          - soundcloud
          - update-android-manifest
