package com.soundcloud.android.utils;

import com.soundcloud.android.SoundCloudApplication;

import java.io.PrintWriter;
import java.io.StringWriter;

public class ErrorUtils {
    /**
     * A convenient way of extracting the stack trace from an
     * exception.
     *
     * @param t The <code>Throwable</code>.
     * @return The stack trace as generated by the exception's
     * <code>printStackTrace(PrintWriter)</code> method.
     */
    public static String getStackTrace(Throwable t)
    {
        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw, true);
        t.printStackTrace(pw);
        return sw.getBuffer().toString();
    }

    public static void reportThrowable(Throwable t){
        SoundCloudApplication.handleSilentException(t.getMessage(), t);
        t.printStackTrace();
    }
}
