package com.soundcloud.android.utils;

import com.soundcloud.android.SoundCloudApplication;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;

public class ErrorUtils {
    /**
     * A convenient way of extracting the stack trace from an
     * exception.
     *
     * @param t The <code>Throwable</code>.
     * @return The stack trace as generated by the exception's
     * <code>printStackTrace(PrintWriter)</code> method.
     */
    public static String getStackTrace(Throwable t)
    {
        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw, true);
        t.printStackTrace(pw);
        return sw.getBuffer().toString();
    }

    /**
     * Use this handler to provide default handling of Throwables in RxJava Observers.
     *
     * By default, RxJava wraps custom observers in a {@link rx.operators.SafeObserver}
     * which catches exceptions like NullPointerExceptions and forwards them to the
     * source observer. This is NOT what we want; we want a NPE to crash the app and be
     * reported as a crash into Crashlytics.
     *
     * This methods ensures that only checked exceptions make their way into an observer's
     * onError method, and also logs them silenty into Crashlytics (unless they're blacklisted.)
     *
     * @param t the Exception or Error that was raised
     */
    public static void handleThrowable(Throwable t) {
        if (t instanceof RuntimeException) {
            throw (RuntimeException) t;
        } else if (t instanceof Error) {
            throw new RuntimeException(t);
        } else if (!excludeFromReports(t)) {
            // don't rethrow checked exceptions
            SoundCloudApplication.handleSilentException(t.getMessage(), t);
        }
        t.printStackTrace();
    }

    private static boolean excludeFromReports(Throwable t) {
        return t instanceof IOException;
    }
}
