autoCorrect: true
failFast: false

test-pattern: # Configure exclusions for test sources
  active: true
  patterns: # Test file regular expressions
    - '.*/test/.*'
    - '.*/androidTest/.*'
    - '.*Test.kt'
    - '.*Spec.kt'
  exclude-rule-sets:
    - 'comments'
  exclude-rules:
    - 'NamingRules'
    - 'WildcardImport'
    - 'MagicNumber'
    - 'MaxLineLength'
    - 'LateInitUsage'
    - 'StringLiteralDuplication'
    - 'UnsafeCast'

build:
  weights:
    complexity: 2
    formatting: 0
    LongParameterList: 1
    comments: 0

processors:
  active: true
  exclude:
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ClassCountProcessor'
  # - 'PackageCountProcessor'
  # - 'KtFileCountProcessor'

console-reports:
  active: true
  exclude:
  #  - 'ProjectStatisticsReport'
  #  - 'ComplexityReport'
  #  - 'NotificationReport'
  #  - 'FindingsReport'
  #  - 'BuildFailureReport'

output-reports:
  active: true
  exclude:
  #  - 'PlainOutputReport'
  #  - 'XmlOutputReport'

potential-bugs:
  active: true
  DuplicateCaseInWhenExpression:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: false
  EqualsWithHashCodeExist:
    active: true
  InvalidLoopCondition:
    active: true
  WrongEqualsTypeParameter:
    active: false
  IteratorHasNextCallsNextMethod:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  UnreachableCode:
    active: true
  LateinitUsage:
    active: false
    excludeAnnotatedProperties: ''
    ignoreOnClassesPattern: ''
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
  UselessPostfixExpression:
    active: true

performance:
  active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: true
    methodNames: 'toString,hashCode,equals,finalize'
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: true
    exceptions:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - IndexOutOfBoundsException
      - InterruptedException
      - NullPointerException
      - RuntimeException
      - Throwable
  TooGenericExceptionThrown:
    active: true
    exceptions:
      - Error
      - Exception
      - NullPointerException
      - RuntimeException
      - Throwable
      - ThrowError
      - ThrowException
      - ThrowNullPointerException
      - ThrowRuntimeException
      - ThrowThrowable
  InstanceOfCheckForException:
    active: true
  NotImplementedDeclaration:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: false
    exceptions: 'IllegalArgumentException,IllegalStateException,IOException'
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 20
  NestedBlockDepth:
    active: true
    threshold: 3
  LongParameterList:
    active: true
    threshold: 5
  LargeClass:
    active: true
    threshold: 150
  ComplexInterface:
    active: false
    threshold: 10
    includeStaticDeclarations: false
  ComplexMethod:
    active: true
    threshold: 10
  MethodOverloading:
    active: false
    threshold: 5
  TooManyFunctions:
    active: false
  ComplexCondition:
    active: true
    threshold: 3
  LabeledExpression:
    active: false
  StringLiteralDuplication:
    active: false
    threshold: 2
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'

code-smell:
  active: true
  FeatureEnvy:
    threshold: 0.5
    weight: 0.45
    base: 0.5

style:
  active: true
  ReturnCount:
    active: true
    max: 2
  ThrowsCount:
    active: true
    max: 2
  NewLineAtEndOfFile:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalWhenBraces:
    active: true
  CollapsibleIfStatements:
    active: true
  EqualsNullCall:
    active: true
  ForbiddenComment:
    active: false
    values: 'TODO:,FIXME:,STOPSHIP:'
  ForbiddenImport:
    active: false
    imports: ''
  PackageDeclarationStyle:
    active: true
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 1
  MethodNameEqualsClassName:
    active: true
    ignoreOverriddenFunction: true
  ModifierOrder:
    active: true
  MagicNumber:
    active: true
    ignoreNumbers: '-1,0,1,2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreEnums: false
  WildcardImport:
    active: true
    excludeImports: 'java.util.*,kotlinx.android.synthetic.*'
  SafeCast:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 200
    excludePackageStatements: false
    excludeImportStatements: false
  PackageNaming:
    active: true
    packagePattern: '^[\w\d.]*$'
  ClassNaming:
    active: true
    classPattern: '^[A-Z][a-zA-Z0-9]*$'
  EnumNaming:
    active: true
    enumEntryPattern: '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'
  FunctionNaming:
    active: true
    functionPattern: '^[a-z][a-zA-Z0-9]*(_[a-zA-Z0-9]+)*$'
  FunctionMaxLength:
    active: false
    maximumFunctionNameLength: 30
  FunctionMinLength:
    active: true
    minimumFunctionNameLength: 2
  VariableNaming:
    active: true
    variablePattern: '^(_)?[a-z$][a-zA-Z$0-9]*$'
  ConstantNaming:
    active: true
    constantPattern: '^([A-Z][A-Z0-9]*(_[A-Z0-9]+)*|FLAG|serialVersionUID_.*)$'
  VariableMaxLength:
    active: false
    maximumVariableNameLength: 30
  VariableMinLength:
    active: true
    minimumVariableNameLength: 2
  ForbiddenClassName:
    active: false
    forbiddenName: ''
  ProtectedMemberInFinalClass:
    active: true
  SerialVersionUIDInSerializableClass:
    active: true
  UnnecessaryParentheses:
    active: true
  UnnecessaryInheritance:
    active: true
  UtilityClassWithPublicConstructor:
    active: true
  DataClassContainsFunctions:
    active: true
    conversionFunctionPrefix: 'to,from'
  UseDataClass:
    active: false
  UnnecessaryAbstractClass:
    active: true
  OptionalUnit:
    active: true
  OptionalReturnKeyword:
    active: true
  ExpressionBodySyntax:
    active: false
  UnusedImports:
    active: true
  NestedClassesVisibility:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  FunctionOnlyReturningConstant:
    active: true
    ignoreOverriddenFunction: true
    excludedFunctions: 'describeContents'

comments:
  active: true
  CommentOverPrivateFunction:
    active: true
  CommentOverPrivateProperty:
    active: true
  UndocumentedPublicClass:
    active: false
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
  UndocumentedPublicFunction:
    active: false

# *experimental feature*
# Migration rules can be defined in the same config file or a new one
migration:
  active: true
  imports:
    # your.package.Class: new.package.or.Class
    # for example:
    # io.gitlab.arturbosch.detekt.api.Rule: io.gitlab.arturbosch.detekt.rule.Rule
