--- !ruby/object:MrLoggerLogger::ResultSpec
expected_events:
- !ruby/object:MrLoggerLogger::Event
  name: audio
  params:
    client_event_id: '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89ab][a-fA-F0-9]{3}-[a-fA-F0-9]{12}'
    anonymous_id: (\w|-)+
    track_owner: soundcloud:users:[0-9]+
    source: stations
    client_id: 3152
    source_version: default
    action: play_start
    player_type: (MediaPlayer|Skippy)
    consumer_subs_plan: high_tier
    page_name: stations:main
    source_urn: soundcloud:[a-zA-Z]+-stations:[0-9]+
    user: soundcloud:users:161646357
    playhead_position: '[0-9]+'
    track_length: '[0-9]+'
    protocol: (https|hls)
    ts: '[0-9]+'
    track: soundcloud:tracks:[0-9]+
    connection_type: wifi
    trigger: manual
    local_storage_playback: false
    policy: (ALLOW|SNIP)
    app_version: '[0-9]+'
    monetization_model: (\w|-)+
  version: '1'
- !ruby/object:MrLoggerLogger::Event
  name: audio
  params:
    client_event_id: '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89ab][a-fA-F0-9]{3}-[a-fA-F0-9]{12}'
    play_id: '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89ab][a-fA-F0-9]{3}-[a-fA-F0-9]{12}'
    anonymous_id: (\w|-)+
    track_owner: soundcloud:users:[0-9]+
    source: stations
    client_id: 3152
    source_version: default
    action: pause
    player_type: (MediaPlayer|Skippy)
    consumer_subs_plan: high_tier
    page_name: stations:main
    source_urn: soundcloud:[a-zA-Z]+-stations:[0-9]+
    user: soundcloud:users:161646357
    playhead_position: '[0-9]+'
    track_length: '[0-9]+'
    protocol: (https|hls)
    ts: '[0-9]+'
    track: soundcloud:tracks:[0-9]+
    connection_type: wifi
    pause_reason: skip
    trigger: manual
    local_storage_playback: false
    policy: (ALLOW|SNIP)
    app_version: '[0-9]+'
    monetization_model: (\w|-)+
  version: '1'
- !ruby/object:MrLoggerLogger::Event
  name: audio
  params:
    client_event_id: '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89ab][a-fA-F0-9]{3}-[a-fA-F0-9]{12}'
    anonymous_id: (\w|-)+
    track_owner: soundcloud:users:[0-9]+
    source: stations
    client_id: 3152
    source_version: default
    action: play_start
    player_type: (MediaPlayer|Skippy)
    consumer_subs_plan: high_tier
    page_name: stations:main
    source_urn: soundcloud:[a-zA-Z]+-stations:[0-9]+
    user: soundcloud:users:161646357
    playhead_position: '[0-9]+'
    track_length: '[0-9]+'
    protocol: (https|hls)
    ts: '[0-9]+'
    track: soundcloud:tracks:[0-9]+
    connection_type: wifi
    trigger: manual
    query_urn: soundcloud:radio:(\w|-)+
    local_storage_playback: false
    policy: (ALLOW|SNIP)
    app_version: '[0-9]+'
    monetization_model: (\w|-)+
  version: '1'
- !ruby/object:MrLoggerLogger::Event
  name: audio
  params:
    client_event_id: '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89ab][a-fA-F0-9]{3}-[a-fA-F0-9]{12}'
    play_id: '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89ab][a-fA-F0-9]{3}-[a-fA-F0-9]{12}'
    anonymous_id: (\w|-)+
    track_owner: soundcloud:users:[0-9]+
    source: stations
    client_id: 3152
    source_version: default
    action: pause
    player_type: (MediaPlayer|Skippy)
    consumer_subs_plan: high_tier
    page_name: stations:main
    source_urn: soundcloud:[a-zA-Z]+-stations:[0-9]+
    user: soundcloud:users:161646357
    playhead_position: '[0-9]+'
    track_length: '[0-9]+'
    protocol: (https|hls)
    ts: '[0-9]+'
    track: soundcloud:tracks:[0-9]+
    connection_type: wifi
    pause_reason: pause
    trigger: manual
    query_urn: soundcloud:radio:(\w|-)+
    local_storage_playback: false
    policy: (ALLOW|SNIP)
    app_version: '[0-9]+'
    monetization_model: (\w|-)+
  version: '1'
whitelisted_events: audio
