--- !ruby/object:MrLoggerLogger::ResultSpec
whitelisted_events:
- audio
expected_events:
- !ruby/object:MrLoggerLogger::Event
  name: audio
  params:
    anonymous_id: (\w|-)+
    track_owner: soundcloud:users:[0-9]+
    source: stations
    client_id: 3152
    source_version: default
    action: play
    player_type: (MediaPlayer|Skippy)
    consumer_subs_plan: none
    page_name: playlists:main
    user: soundcloud:users:161646357
    playhead_position: '[0-9]+'
    track_length: '[0-9]+'
    protocol: (https|hls)
    ts: '[0-9]+'
    track: soundcloud:tracks:[0-9]+
    connection_type: wifi
    trigger: manual
    query_urn: soundcloud:track-stations:98576331
    local_storage_playback: false
  version: '1'
- !ruby/object:MrLoggerLogger::Event
  name: audio
  params:
    anonymous_id: (\w|-)+
    track_owner: soundcloud:users:[0-9]+
    source: stations
    client_id: 3152
    source_version: default
    action: pause
    player_type: (MediaPlayer|Skippy)
    consumer_subs_plan: none
    page_name: playlists:main
    user: soundcloud:users:161646357
    playhead_position: '[0-9]+'
    track_length: '[0-9]+'
    protocol: (https|hls)
    ts: '[0-9]+'
    track: soundcloud:tracks:[0-9]+
    connection_type: wifi
    reason: pause
    trigger: manual
    query_urn: soundcloud:track-stations:98576331
    local_storage_playback: false
  version: '1'
