--- !ruby/object:MrLoggerLogger::ResultSpec
expected_events:
- !ruby/object:MrLoggerLogger::Event
  name: audio
  params:
    anonymous_id: (\w|-)+
    source: recommender
    client_id: '[0-9]+'
    source_version: naive-source
    action: play
    player_type: Skippy
    track: soundcloud:tracks:[0-9]+
    track_length: '[0-9]+'
    page_name: playlists:main
    user: soundcloud:users:161646357
    playhead_position: '[0-9]+'
    track_owner: soundcloud:users:[0-9]+
    protocol: hls
    ts: '[0-9]+'
    connection_type: wifi
    trigger: manual
    consumer_subs_plan: none
    local_storage_playback: false
  version: '0'
- !ruby/object:MrLoggerLogger::Event
  name: audio
  params:
    anonymous_id: (\w|-)+
    source: recommender
    client_id: '[0-9]+'
    source_version: naive-source
    action: pause
    player_type: Skippy
    track: soundcloud:tracks:[0-9]+
    track_length: '[0-9]+'
    page_name: playlists:main
    user: soundcloud:users:161646357
    playhead_position: '[0-9]+'
    track_owner: soundcloud:users:[0-9]+
    protocol: hls
    ts: '[0-9]+'
    connection_type: wifi
    reason: skip
    trigger: manual
    consumer_subs_plan: none
    local_storage_playback: false
  version: '0'
- !ruby/object:MrLoggerLogger::Event
  name: audio
  params:
    protocol: hls
    anonymous_id: (\w|-)+
    ts: '[0-9]+'
    client_id: '[0-9]+'
    connection_type: wifi
    action: play
    player_type: Skippy
    trigger: manual
    track: soundcloud:tracks:[0-9]+
    track_length: '[0-9]+'
    page_name: playlists:main
    user: soundcloud:users:161646357
    playhead_position: '[0-9]+'
    track_owner: soundcloud:users:[0-9]+
    consumer_subs_plan: none
    local_storage_playback: false
  version: '0'
- !ruby/object:MrLoggerLogger::Event
  name: audio
  params:
    protocol: hls
    anonymous_id: (\w|-)+
    ts: '[0-9]+'
    client_id: '[0-9]+'
    connection_type: wifi
    action: pause
    reason: track_finished
    player_type: Skippy
    trigger: manual
    track: soundcloud:tracks:[0-9]+
    track_length: '[0-9]+'
    page_name: playlists:main
    user: soundcloud:users:161646357
    playhead_position: '[0-9]+'
    track_owner: soundcloud:users:[0-9]+
    consumer_subs_plan: none
    local_storage_playback: false
  version: '0'
- !ruby/object:MrLoggerLogger::Event
  name: audio
  params:
    anonymous_id: (\w|-)+
    source: recommender
    client_id: '[0-9]+'
    source_version: naive-source
    action: play
    player_type: Skippy
    track: soundcloud:tracks:[0-9]+
    track_length: '[0-9]+'
    page_name: playlists:main
    user: soundcloud:users:161646357
    playhead_position: '[0-9]+'
    track_owner: soundcloud:users:[0-9]+
    protocol: hls
    ts: '[0-9]+'
    connection_type: wifi
    trigger: auto
    consumer_subs_plan: none
    local_storage_playback: false
  version: '0'
whitelisted_events: audio
