package com.soundcloud.android.sync;

public enum Syncable {
    SOUNDSTREAM,
    ACTIVITIES,
    TRACK_LIKES,
    PLAYLIST_LIKES,
    TRACK_POSTS,
    PLAYLIST_POSTS,
    RECENT_STATIONS,
    RECOMMENDED_STATIONS,
    RECOMMENDED_TRACKS,
    CHARTS,
    CHART_GENRES,
    TRACKS,
    PLAYLISTS,
    USERS,
    PLAYLIST,
    PLAY_HISTORY
}
