CREATE TABLE Tracks (_id INTEGER PRIMARY KEY AUTOINCREMENT,last_updated INTEGER,permalink VARCHAR(255),duration INTEGER,created_at INTEGER,tag_list VARCHAR(255),track_type VARCHAR(255),title VARCHAR(255),permalink_url VARCHAR(255),artwork_url VARCHAR(255), waveform_url VARCHAR(255), downloadable BOOLEAN, commentable BOOLEAN, download_url VARCHAR(255), stream_url VARCHAR(255),streamable BOOLEAN DEFAULT 0, sharing VARCHAR(255),playback_count INTEGER,download_count INTEGER,comment_count INTEGER,favoritings_count INTEGER,shared_to_count INTEGER,sharing_note_text VARCHAR(255),user_id INTEGER);
CREATE TABLE TrackMetadata (_id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER, play_count INTEGER DEFAULT 0,cached INTEGER DEFAULT 0,type INTEGER DEFAULT 0,etag VARCHAR(34),url_hash VARCHAR(32),size INTEGER,bitrate INTEGER,UNIQUE (_id, user_id) ON CONFLICT IGNORE);
CREATE TABLE Users (_id INTEGER PRIMARY KEY AUTOINCREMENT,username VARCHAR(255),avatar_url VARCHAR(255),permalink VARCHAR(255),permalink_url VARCHAR(255),full_name VARCHAR(255),description text,city VARCHAR(255),country VARCHAR(255),plan VARCHAR(16),primary_email_confirmed INTEGER,website VARCHAR(255),website_title VARCHAR(255), discogs_name VARCHAR(255),myspace_name VARCHAR(255),track_count INTEGER,followers_count INTEGER,followings_count INTEGER,public_favorites_count INTEGER,private_tracks_count INTEGER,last_updated INTEGER);
CREATE TABLE Comments (_id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,track_id INTEGER,timestamp INTEGER,created_at INTEGER,body VARCHAR(255));
CREATE TABLE Activities (_id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,track_id INTEGER,comment_id INTEGER,type VARCHAR(255),tags VARCHAR(255),created_at INTEGER,content_id INTEGER,UNIQUE (created_at, type, content_id, track_id, user_id));
CREATE TABLE Recordings (_id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,timestamp INTEGER,longitude VARCHAR(255),latitude VARCHAR(255),what_text VARCHAR(255),where_text VARCHAR(255),audio_path VARCHAR(255),artwork_path VARCHAR(255),duration INTEGER,four_square_venue_id VARCHAR(255), shared_emails text,shared_ids text, private_user_id INTEGER,service_ids VARCHAR(255),is_private BOOLEAN,external_upload BOOLEAN,audio_profile INTEGER,upload_status INTEGER DEFAULT 0,upload_error BOOLEAN);
CREATE TABLE Searches (_id INTEGER PRIMARY KEY AUTOINCREMENT,created_at INTEGER,user_id INTEGER,query VARCHAR(255),search_type INTEGER,UNIQUE (user_id, search_type, query) ON CONFLICT REPLACE);
CREATE TABLE Playlist (_id INTEGER PRIMARY KEY AUTOINCREMENT,created_at INTEGER,position INTEGER,seek_pos INTEGER,user_id INTEGER);
CREATE TABLE PlaylistItems (_id INTEGER PRIMARY KEY AUTOINCREMENT,playlist_id INTEGER,track_id INTEGER,position INTEGER,user_id INTEGER, UNIQUE (track_id, position, user_id) ON CONFLICT IGNORE);
CREATE TABLE CollectionItems (user_id INTEGER, item_id INTEGER,collection_type INTEGER, position INTEGER, PRIMARY KEY(user_id, item_id, collection_type) ON CONFLICT REPLACE);
CREATE TABLE Collections (_id INTEGER PRIMARY KEY AUTOINCREMENT,uri VARCHAR(255),last_addition INTEGER, last_sync INTEGER, size INTEGER, sync_state INTEGER, extra VARCHAR(255), UNIQUE (uri));
CREATE TABLE CollectionPages (collection_id INTEGER,page_index INTEGER,etag VARCHAR(255), size INTEGER, PRIMARY KEY(collection_id, page_index) ON CONFLICT REPLACE);
CREATE VIEW TrackView AS SELECT Tracks._id as _id,Tracks.last_updated as last_updated,Tracks.permalink as permalink,Tracks.created_at as created_at,Tracks.duration as duration,Tracks.tag_list as tag_list,Tracks.track_type as track_type,Tracks.title as title,Tracks.permalink_url as permalink_url,Tracks.artwork_url as artwork_url,Tracks.waveform_url as waveform_url,Tracks.downloadable as downloadable,Tracks.download_url as download_url,Tracks.stream_url as stream_url,Tracks.streamable as streamable,Tracks.commentable as commentable,Tracks.sharing as sharing,Tracks.playback_count as playback_count,Tracks.download_count as download_count,Tracks.comment_count as comment_count,Tracks.favoritings_count as favoritings_count,Tracks.shared_to_count as shared_to_count,Tracks.sharing_note_text as sharing_note_text,Users._id as track_user_id,Users.username as track_user_username,Users.permalink as track_user_permalink,Users.avatar_url as track_user_avatar_url,COALESCE(TrackMetadata.play_count, 0) as track_user_play_count,COALESCE(TrackMetadata.cached, 0) as track_cached,COALESCE(TrackMetadata.type, 0) as track_type FROM Tracks JOIN Users ON(   Tracks.user_id = Users._id) LEFT OUTER JOIN TrackMetadata ON(   TrackMetadata._id = Tracks._id)
CREATE VIEW ActivityView AS SELECT Activities._id as _id,Activities.type as type,Activities.tags as tags,Activities.created_at as created_at,Activities.comment_id as comment_id,Activities.track_id as track_id,Activities.user_id as user_id,Activities.content_id as content_id,Users.username as activity_user_username,Users.permalink as activity_user_permalink,Users.avatar_url as activity_user_avatar_url,TrackView.*,Comments.body as comment_body,Comments.created_at as comment_created_at,Comments.timestamp as comment_timestamp FROM Activities JOIN Users ON(   Activities.user_id = Users._id) JOIN TrackView ON(   Activities.track_id = TrackView._id) LEFT JOIN Comments ON(   Activities.comment_id = Comments._id) LEFT JOIN Activities dup ON(   dup.track_id = Activities.track_id AND dup.type='track-sharing' AND Activities.type = 'track') WHERE dup._id IS NULL ORDER BY created_at DESC
