/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soundcloud_android_jni_VorbisDecoder */

#ifndef _Included_com_soundcloud_android_jni_VorbisDecoder
#define _Included_com_soundcloud_android_jni_VorbisDecoder
#ifdef __cplusplus
extern "C" {
#endif
#undef com_soundcloud_android_jni_VorbisDecoder_ALIGN_SEEK_ON_PAGE
#define com_soundcloud_android_jni_VorbisDecoder_ALIGN_SEEK_ON_PAGE 0L
/*
 * Class:     com_soundcloud_android_jni_VorbisDecoder
 * Method:    getState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_VorbisDecoder_getState
  (JNIEnv *, jobject);

/*
 * Class:     com_soundcloud_android_jni_VorbisDecoder
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_soundcloud_android_jni_VorbisDecoder_release
  (JNIEnv *, jobject);

/*
 * Class:     com_soundcloud_android_jni_VorbisDecoder
 * Method:    getInfo
 * Signature: ()Lcom/soundcloud/android/jni/Info;
 */
JNIEXPORT jobject JNICALL Java_com_soundcloud_android_jni_VorbisDecoder_getInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_soundcloud_android_jni_VorbisDecoder
 * Method:    decode
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_VorbisDecoder_decode
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_soundcloud_android_jni_VorbisDecoder
 * Method:    pcmSeek
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_VorbisDecoder_pcmSeek
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_soundcloud_android_jni_VorbisDecoder
 * Method:    timeSeek
 * Signature: (DZ)I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_VorbisDecoder_timeSeek
  (JNIEnv *, jobject, jdouble, jboolean);

/*
 * Class:     com_soundcloud_android_jni_VorbisDecoder
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_VorbisDecoder_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_soundcloud_android_jni_VorbisDecoder
 * Method:    decodeToFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_VorbisDecoder_decodeToFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
