/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soundcloud_android_jni_VorbisDecoder */

#ifndef _Included_com_soundcloud_android_jni_VorbisDecoder
#define _Included_com_soundcloud_android_jni_VorbisDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soundcloud_android_jni_VorbisDecoder
 * Method:    getInfo
 * Signature: ()Lcom/soundcloud/android/jni/Info;
 */
JNIEXPORT jobject JNICALL Java_com_soundcloud_android_jni_VorbisDecoder_getInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_soundcloud_android_jni_VorbisDecoder
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_VorbisDecoder_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_soundcloud_android_jni_VorbisDecoder
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_soundcloud_android_jni_VorbisDecoder_release
  (JNIEnv *, jobject);

/*
 * Class:     com_soundcloud_android_jni_VorbisDecoder
 * Method:    decode
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_VorbisDecoder_decode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_soundcloud_android_jni_VorbisDecoder
 * Method:    decodeToFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_VorbisDecoder_decodeToFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
