/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soundcloud_android_jni_VorbisEncoder */

#ifndef _Included_com_soundcloud_android_jni_VorbisEncoder
#define _Included_com_soundcloud_android_jni_VorbisEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soundcloud_android_jni_VorbisEncoder
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;JJF)I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_VorbisEncoder_init
  (JNIEnv *, jobject, jstring, jstring, jlong, jlong, jfloat);

/*
 * Class:     com_soundcloud_android_jni_VorbisEncoder
 * Method:    write
 * Signature: (Ljava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_VorbisEncoder_write
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_soundcloud_android_jni_VorbisEncoder
 * Method:    pause
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_VorbisEncoder_pause
  (JNIEnv *, jobject);

/*
 * Class:     com_soundcloud_android_jni_VorbisEncoder
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_soundcloud_android_jni_VorbisEncoder_release
  (JNIEnv *, jobject);

/*
 * Class:     com_soundcloud_android_jni_VorbisEncoder
 * Method:    getState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_soundcloud_android_jni_VorbisEncoder_getState
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
